class_name CardCatalog
extends RefCounted

## Catálogo canónico Nexo de Runas — Acto I.
## 94 cartas visuales normalizadas. La identidad visual proviene de las seis
## láminas aprobadas; coste, ATQ, VIDA y sellos base proceden de los datos
## mecánicos de las cartas equivalentes de Inscryption.
const SIGIL_NAMES := {"TOUCH_OF_DEATH":"TOQUE MORTAL", "LEADER":"LÍDER", "AMORPHOUS":"AMORFO", "ANT_SPAWNER":"GENERADOR DE HORMIGAS", "AIRBORNE":"AÉREO", "DAM_BUILDER":"CONSTRUCTOR DE REPRESAS", "BEES_WITHIN":"COLMENA", "WORTHY_SACRIFICE":"SACRIFICIO DIGNO", "GUARDIAN":"GUARDIÁN", "MIGHTY_LEAP":"SALTO PODEROSO", "MANY_LIVES":"MUCHAS VIDAS", "UNKILLABLE":"INMORTAL", "CORPSE_EATER":"DEVORADOR DE CADÁVERES", "SPRINTER":"CORREDOR", "FLEDGLING":"CRÍA", "FECUNDITY":"FECUNDIDAD", "FROZEN_AWAY":"CONGELADO", "BONE_KING":"REY DE HUESOS", "WATERBORNE":"SUMERGIBLE", "STEEL_TRAP":"TRAMPA DE ACERO", "HOARDER":"ACAPARADOR", "BIFURCATED_STRIKE":"GOLPE BIFURCADO", "TRIFURCATED_STRIKE":"GOLPE TRIFURCADO", "BURROWER":"MADRIGUERA", "HEFTY":"PESADO", "TRINKET_BEARER":"PORTADOR DE OBJETO", "SHARP_QUILLS":"ESPINAS", "RABBIT_HOLE":"MADRIGUERA DE CONEJOS", "STINKY":"HEDOR", "LOOSE_TAIL":"COLA SUELTA", "BELLIST":"CAMPANERO", "REPULSIVE":"REPULSIVO"}

const CARDS := [
	{"id":"vibora", "name":"VÍBORA", "source_id":"Adder", "resource":"blood", "cost_value":2, "cost":"2 SANGRE", "atk":1, "hp":1, "sigils":["TOUCH_OF_DEATH"], "seal":"TOQUE MORTAL", "special_stat":"NONE", "special_abilities":[], "traits":["KillsSurvivors"], "tribes":["Reptile"], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":1, "visual_row":1, "visual_col":1},
	{"id":"lobo_alfa", "name":"LOBO ALFA", "source_id":"Alpha", "resource":"bones", "cost_value":4, "cost":"4 HUESOS", "atk":1, "hp":2, "sigils":["LEADER"], "seal":"LÍDER", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":["Canine"], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":1, "visual_row":1, "visual_col":2},
	{"id":"amalgama", "name":"AMALGAMA", "source_id":"Amalgam", "resource":"blood", "cost_value":2, "cost":"2 SANGRE", "atk":3, "hp":3, "sigils":[], "seal":"NINGUNO", "special_stat":"NONE", "special_abilities":[], "traits":["Ant"], "tribes":["Bird", "Canine", "Hooved", "Reptile", "Insect", "Squirrel"], "rare":true, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":true, "visual_page":1, "visual_row":1, "visual_col":3},
	{"id":"ameba", "name":"AMEBA", "source_id":"Amoeba", "resource":"bones", "cost_value":2, "cost":"2 HUESOS", "atk":1, "hp":2, "sigils":["AMORPHOUS"], "seal":"AMORFO", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":[], "rare":true, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":1, "visual_row":1, "visual_col":4},
	{"id":"reina_hormiga", "name":"REINA HORMIGA", "source_id":"AntQueen", "resource":"blood", "cost_value":2, "cost":"2 SANGRE", "atk":0, "hp":3, "sigils":["ANT_SPAWNER"], "seal":"GENERADOR DE HORMIGAS", "special_stat":"ANTS", "special_abilities":["Ant"], "traits":["Ant"], "tribes":["Insect"], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":true, "visual_page":1, "visual_row":2, "visual_col":1},
	{"id":"cubo_cebo", "name":"CUBO CEBO", "source_id":"BaitBucket", "resource":"none", "cost_value":0, "cost":"SIN COSTE", "atk":0, "hp":1, "sigils":[], "seal":"NINGUNO", "special_stat":"NONE", "special_abilities":[], "traits":["Structure", "Terrain"], "tribes":[], "rare":false, "rewardable":false, "playable":false, "structure":true, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"gran_tiburon_blanco", "tail_spawn":"", "counts_as_ant":false, "visual_page":1, "visual_row":2, "visual_col":2},
	{"id":"murcielago", "name":"MURCIÉLAGO", "source_id":"Bat", "resource":"bones", "cost_value":4, "cost":"4 HUESOS", "atk":2, "hp":1, "sigils":["AIRBORNE"], "seal":"AÉREO", "special_stat":"NONE", "special_abilities":[], "traits":["Blind"], "tribes":[], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":1, "visual_row":2, "visual_col":3},
	{"id":"castor", "name":"CASTOR", "source_id":"Beaver", "resource":"blood", "cost_value":2, "cost":"2 SANGRE", "atk":1, "hp":4, "sigils":["DAM_BUILDER"], "seal":"CONSTRUCTOR DE REPRESAS", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":[], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":1, "visual_row":2, "visual_col":4},
	{"id":"abeja", "name":"ABEJA", "source_id":"Bee", "resource":"none", "cost_value":0, "cost":"SIN COSTE", "atk":1, "hp":1, "sigils":["AIRBORNE"], "seal":"AÉREO", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":["Insect"], "rare":false, "rewardable":false, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":1, "visual_row":3, "visual_col":1},
	{"id":"colmena", "name":"COLMENA", "source_id":"Beehive", "resource":"blood", "cost_value":1, "cost":"1 SANGRE", "atk":0, "hp":2, "sigils":["BEES_WITHIN"], "seal":"COLMENA", "special_stat":"NONE", "special_abilities":[], "traits":["Structure"], "tribes":["Insect"], "rare":false, "rewardable":false, "playable":true, "structure":true, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":1, "visual_row":3, "visual_col":2},
	{"id":"cabra_negra", "name":"CABRA NEGRA", "source_id":"Goat", "resource":"blood", "cost_value":1, "cost":"1 SANGRE", "atk":0, "hp":1, "sigils":["WORTHY_SACRIFICE"], "seal":"SACRIFICIO DIGNO", "special_stat":"NONE", "special_abilities":[], "traits":["Goat"], "tribes":["Hooved"], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":1, "visual_row":3, "visual_col":3},
	{"id":"cabra_negra_alt", "name":"CABRA NEGRA (ALT.)", "source_id":"Goat", "resource":"blood", "cost_value":1, "cost":"1 SANGRE", "atk":0, "hp":1, "sigils":["WORTHY_SACRIFICE"], "seal":"SACRIFICIO DIGNO", "special_stat":"NONE", "special_abilities":[], "traits":["Goat"], "tribes":["Hooved"], "rare":false, "rewardable":false, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":1, "visual_row":3, "visual_col":4},
	{"id":"carta_vacia", "name":"CARTA VACÍA", "source_id":"", "resource":"none", "cost_value":0, "cost":"SIN COSTE", "atk":0, "hp":0, "sigils":[], "seal":"NINGUNO", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":[], "rare":false, "rewardable":false, "playable":false, "structure":false, "side_deck":false, "special_only":true, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":1, "visual_row":4, "visual_col":1},
	{"id":"sabueso", "name":"SABUESO", "source_id":"Bloodhound", "resource":"blood", "cost_value":2, "cost":"2 SANGRE", "atk":2, "hp":3, "sigils":["GUARDIAN"], "seal":"GUARDIÁN", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":["Canine"], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":1, "visual_row":4, "visual_col":2},
	{"id":"roca", "name":"ROCA", "source_id":"Boulder", "resource":"none", "cost_value":0, "cost":"SIN COSTE", "atk":0, "hp":5, "sigils":[], "seal":"NINGUNO", "special_stat":"NONE", "special_abilities":[], "traits":["Structure", "Terrain"], "tribes":[], "rare":false, "rewardable":false, "playable":true, "structure":true, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":1, "visual_row":4, "visual_col":3},
	{"id":"rana_toro", "name":"RANA TORO", "source_id":"Bullfrog", "resource":"blood", "cost_value":1, "cost":"1 SANGRE", "atk":1, "hp":2, "sigils":["MIGHTY_LEAP"], "seal":"SALTO PODEROSO", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":["Reptile"], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":1, "visual_row":4, "visual_col":4},
	{"id":"lobo_enjaulado", "name":"LOBO ENJAULADO", "source_id":"CagedWolf", "resource":"blood", "cost_value":2, "cost":"2 SANGRE", "atk":0, "hp":6, "sigils":[], "seal":"NINGUNO", "special_stat":"NONE", "special_abilities":["CagedWolf"], "traits":["Structure", "Terrain", "DeathcardCreationNonOption"], "tribes":["Canine"], "rare":false, "rewardable":false, "playable":true, "structure":true, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":2, "visual_row":1, "visual_col":1},
	{"id":"gato", "name":"GATO", "source_id":"Cat", "resource":"blood", "cost_value":1, "cost":"1 SANGRE", "atk":0, "hp":1, "sigils":["MANY_LIVES"], "seal":"MUCHAS VIDAS", "special_stat":"NONE", "special_abilities":["Cat"], "traits":[], "tribes":[], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":2, "visual_row":1, "visual_col":2},
	{"id":"nino_13", "name":"NIÑO 13", "source_id":"JerseyDevil", "resource":"blood", "cost_value":1, "cost":"1 SANGRE", "atk":0, "hp":1, "sigils":["MANY_LIVES"], "seal":"MUCHAS VIDAS", "special_stat":"NONE", "special_abilities":["JerseyDevil"], "traits":[], "tribes":["Hooved"], "rare":true, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":2, "visual_row":1, "visual_col":3},
	{"id":"nino_13_despierto", "name":"NIÑO 13 DESPIERTO", "source_id":"", "resource":"blood", "cost_value":1, "cost":"1 SANGRE", "atk":2, "hp":1, "sigils":["AIRBORNE", "MANY_LIVES"], "seal":"AÉREO", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":[], "rare":false, "rewardable":false, "playable":false, "structure":false, "side_deck":false, "special_only":true, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":2, "visual_row":1, "visual_col":4},
	{"id":"campanilla", "name":"CAMPANILLA", "source_id":"DausBell", "resource":"none", "cost_value":0, "cost":"SIN COSTE", "atk":0, "hp":1, "sigils":[], "seal":"NINGUNO", "special_stat":"NONE", "special_abilities":[], "traits":["Structure", "Terrain"], "tribes":[], "rare":false, "rewardable":false, "playable":false, "structure":true, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":2, "visual_row":2, "visual_col":1},
	{"id":"cucaracha", "name":"CUCARACHA", "source_id":"Cockroach", "resource":"bones", "cost_value":4, "cost":"4 HUESOS", "atk":1, "hp":1, "sigils":["UNKILLABLE"], "seal":"INMORTAL", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":["Insect"], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":2, "visual_row":2, "visual_col":2},
	{"id":"gusanos_cadavericos", "name":"GUSANOS CADAVÉRICOS", "source_id":"Maggots", "resource":"bones", "cost_value":5, "cost":"5 HUESOS", "atk":1, "hp":2, "sigils":["CORPSE_EATER"], "seal":"DEVORADOR DE CADÁVERES", "special_stat":"NONE", "special_abilities":[], "traits":["Blind"], "tribes":["Insect"], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":2, "visual_row":2, "visual_col":3},
	{"id":"coyote", "name":"COYOTE", "source_id":"Coyote", "resource":"bones", "cost_value":4, "cost":"4 HUESOS", "atk":2, "hp":1, "sigils":[], "seal":"NINGUNO", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":["Canine"], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":2, "visual_row":2, "visual_col":4},
	{"id":"represa", "name":"REPRESA", "source_id":"Dam", "resource":"none", "cost_value":0, "cost":"SIN COSTE", "atk":0, "hp":2, "sigils":[], "seal":"NINGUNO", "special_stat":"NONE", "special_abilities":[], "traits":["Structure", "Terrain"], "tribes":[], "rare":false, "rewardable":false, "playable":false, "structure":true, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":2, "visual_row":3, "visual_col":1},
	{"id":"alce", "name":"ALCE", "source_id":"Elk", "resource":"blood", "cost_value":2, "cost":"2 SANGRE", "atk":2, "hp":4, "sigils":["SPRINTER"], "seal":"CORREDOR", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":["Hooved"], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":2, "visual_row":3, "visual_col":2},
	{"id":"cria_de_alce", "name":"CRÍA DE ALCE", "source_id":"ElkCub", "resource":"blood", "cost_value":1, "cost":"1 SANGRE", "atk":1, "hp":1, "sigils":["SPRINTER", "FLEDGLING"], "seal":"CORREDOR", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":["Hooved"], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"alce", "evolve_turns":1, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":2, "visual_row":3, "visual_col":3},
	{"id":"ratones_de_campo", "name":"RATONES DE CAMPO", "source_id":"FieldMouse", "resource":"blood", "cost_value":2, "cost":"2 SANGRE", "atk":2, "hp":2, "sigils":["FECUNDITY"], "seal":"FECUNDIDAD", "special_stat":"NONE", "special_abilities":[], "traits":["FeedsStoat"], "tribes":[], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":2, "visual_row":3, "visual_col":4},
	{"id":"zarigueya_helada", "name":"ZARIGÜEYA HELADA", "source_id":"FrozenOpossum", "resource":"none", "cost_value":0, "cost":"SIN COSTE", "atk":0, "hp":5, "sigils":["FROZEN_AWAY"], "seal":"CONGELADO", "special_stat":"NONE", "special_abilities":[], "traits":["Structure", "Terrain"], "tribes":[], "rare":false, "rewardable":false, "playable":false, "structure":true, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"zarigueya", "tail_spawn":"", "counts_as_ant":false, "visual_page":2, "visual_row":4, "visual_col":1},
	{"id":"cola_peluda", "name":"COLA PELUDA", "source_id":"Tail_Furry", "resource":"none", "cost_value":0, "cost":"SIN COSTE", "atk":0, "hp":2, "sigils":[], "seal":"NINGUNO", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":[], "rare":false, "rewardable":false, "playable":false, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":2, "visual_row":4, "visual_col":2},
	{"id":"gecko", "name":"GECKO", "source_id":"Geck", "resource":"none", "cost_value":0, "cost":"SIN COSTE", "atk":1, "hp":1, "sigils":[], "seal":"NINGUNO", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":["Reptile"], "rare":true, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":2, "visual_row":4, "visual_col":3},
	{"id":"pepita_de_oro", "name":"PEPITA DE ORO", "source_id":"GoldNugget", "resource":"none", "cost_value":0, "cost":"SIN COSTE", "atk":0, "hp":2, "sigils":[], "seal":"NINGUNO", "special_stat":"NONE", "special_abilities":[], "traits":["Structure", "Terrain"], "tribes":[], "rare":false, "rewardable":false, "playable":false, "structure":true, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":2, "visual_row":4, "visual_col":4},
	{"id":"pelaje_dorado", "name":"PELAJE DORADO", "source_id":"PeltGolden", "resource":"none", "cost_value":0, "cost":"SIN COSTE", "atk":0, "hp":3, "sigils":[], "seal":"NINGUNO", "special_stat":"NONE", "special_abilities":["SpawnLice"], "traits":["Pelt"], "tribes":[], "rare":false, "rewardable":false, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":3, "visual_row":1, "visual_col":1},
	{"id":"gran_abeto", "name":"GRAN ABETO", "source_id":"Tree", "resource":"none", "cost_value":0, "cost":"SIN COSTE", "atk":0, "hp":3, "sigils":["MIGHTY_LEAP"], "seal":"SALTO PODEROSO", "special_stat":"NONE", "special_abilities":[], "traits":["Structure", "Terrain"], "tribes":[], "rare":false, "rewardable":false, "playable":false, "structure":true, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":3, "visual_row":1, "visual_col":2},
	{"id":"gran_tiburon_blanco", "name":"GRAN TIBURÓN BLANCO", "source_id":"Shark", "resource":"blood", "cost_value":3, "cost":"3 SANGRE", "atk":4, "hp":2, "sigils":["WATERBORNE"], "seal":"SUMERGIBLE", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":[], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":3, "visual_row":1, "visual_col":3},
	{"id":"humo_mayor", "name":"HUMO MAYOR", "source_id":"Smoke_Improved", "resource":"none", "cost_value":0, "cost":"SIN COSTE", "atk":1, "hp":3, "sigils":["BONE_KING"], "seal":"REY DE HUESOS", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":[], "rare":false, "rewardable":false, "playable":false, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":3, "visual_row":1, "visual_col":4},
	{"id":"oso_grizzly", "name":"OSO GRIZZLY", "source_id":"Grizzly", "resource":"blood", "cost_value":3, "cost":"3 SANGRE", "atk":4, "hp":6, "sigils":[], "seal":"NINGUNO", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":[], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":3, "visual_row":2, "visual_col":1},
	{"id":"nino_hambriento", "name":"NIÑO HAMBRIENTO", "source_id":"", "resource":"none", "cost_value":0, "cost":"SIN COSTE", "atk":0, "hp":1, "sigils":[], "seal":"NINGUNO", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":[], "rare":false, "rewardable":false, "playable":false, "structure":false, "side_deck":false, "special_only":true, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":3, "visual_row":2, "visual_col":2},
	{"id":"martin_pescador", "name":"MARTÍN PESCADOR", "source_id":"Kingfisher", "resource":"blood", "cost_value":1, "cost":"1 SANGRE", "atk":1, "hp":1, "sigils":["AIRBORNE", "WATERBORNE"], "seal":"AÉREO", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":["Bird"], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":3, "visual_row":2, "visual_col":3},
	{"id":"trampa_saltarina", "name":"TRAMPA SALTARINA", "source_id":"Trap", "resource":"none", "cost_value":0, "cost":"SIN COSTE", "atk":0, "hp":1, "sigils":["MIGHTY_LEAP", "STEEL_TRAP"], "seal":"SALTO PODEROSO", "special_stat":"NONE", "special_abilities":[], "traits":["Structure", "Terrain"], "tribes":[], "rare":false, "rewardable":false, "playable":false, "structure":true, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":3, "visual_row":2, "visual_col":4},
	{"id":"leshy", "name":"LESHY", "source_id":"", "resource":"blood", "cost_value":1, "cost":"1 SANGRE", "atk":0, "hp":3, "sigils":[], "seal":"NINGUNO", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":[], "rare":false, "rewardable":false, "playable":false, "structure":false, "side_deck":false, "special_only":true, "boss_only":true, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":3, "visual_row":3, "visual_col":1},
	{"id":"alce_largo", "name":"ALCE LARGO", "source_id":"Snelk", "resource":"bones", "cost_value":4, "cost":"4 HUESOS", "atk":1, "hp":2, "sigils":["SPRINTER", "TOUCH_OF_DEATH"], "seal":"CORREDOR", "special_stat":"NONE", "special_abilities":[], "traits":["KillsSurvivors"], "tribes":["Hooved"], "rare":true, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":3, "visual_row":3, "visual_col":2},
	{"id":"urraca", "name":"URRACA", "source_id":"Magpie", "resource":"blood", "cost_value":2, "cost":"2 SANGRE", "atk":1, "hp":1, "sigils":["AIRBORNE", "HOARDER"], "seal":"AÉREO", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":["Bird"], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":3, "visual_row":3, "visual_col":3},
	{"id":"mantis", "name":"MANTIS", "source_id":"Mantis", "resource":"blood", "cost_value":1, "cost":"1 SANGRE", "atk":1, "hp":1, "sigils":["BIFURCATED_STRIKE"], "seal":"GOLPE BIFURCADO", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":["Insect"], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":3, "visual_row":3, "visual_col":4},
	{"id":"dios_mantis", "name":"DIOS MANTIS", "source_id":"MantisGod", "resource":"blood", "cost_value":1, "cost":"1 SANGRE", "atk":1, "hp":1, "sigils":["TRIFURCATED_STRIKE"], "seal":"GOLPE TRIFURCADO", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":["Insect"], "rare":true, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":3, "visual_row":4, "visual_col":1},
	{"id":"topo", "name":"TOPO", "source_id":"Mole", "resource":"blood", "cost_value":1, "cost":"1 SANGRE", "atk":0, "hp":4, "sigils":["BURROWER"], "seal":"MADRIGUERA", "special_stat":"NONE", "special_abilities":[], "traits":["Blind"], "tribes":[], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":3, "visual_row":4, "visual_col":2},
	{"id":"hombre_topo", "name":"HOMBRE TOPO", "source_id":"MoleMan", "resource":"blood", "cost_value":1, "cost":"1 SANGRE", "atk":0, "hp":6, "sigils":["BURROWER", "MIGHTY_LEAP"], "seal":"MADRIGUERA", "special_stat":"NONE", "special_abilities":[], "traits":["Blind"], "tribes":[], "rare":true, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":3, "visual_row":4, "visual_col":3},
	{"id":"alce_macho", "name":"ALCE MACHO", "source_id":"Moose", "resource":"blood", "cost_value":3, "cost":"3 SANGRE", "atk":3, "hp":7, "sigils":["HEFTY"], "seal":"PESADO", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":["Hooved"], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":3, "visual_row":4, "visual_col":4},
	{"id":"hombre_polilla", "name":"HOMBRE POLILLA", "source_id":"Mothman_Stage3", "resource":"blood", "cost_value":1, "cost":"1 SANGRE", "atk":7, "hp":3, "sigils":["AIRBORNE"], "seal":"AÉREO", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":["Insect"], "rare":false, "rewardable":false, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":4, "visual_row":1, "visual_col":1},
	{"id":"zarigueya", "name":"ZARIGÜEYA", "source_id":"Opossum", "resource":"bones", "cost_value":2, "cost":"2 HUESOS", "atk":1, "hp":1, "sigils":[], "seal":"NINGUNO", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":[], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":4, "visual_row":1, "visual_col":2},
	{"id":"uroboros", "name":"UROBOROS", "source_id":"Ouroboros", "resource":"blood", "cost_value":2, "cost":"2 SANGRE", "atk":1, "hp":1, "sigils":["UNKILLABLE"], "seal":"INMORTAL", "special_stat":"NONE", "special_abilities":["Ouroboros"], "traits":["SatisfiesRingTrial"], "tribes":["Reptile"], "rare":true, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":4, "visual_row":1, "visual_col":3},
	{"id":"mula_de_carga", "name":"MULA DE CARGA", "source_id":"Mule", "resource":"none", "cost_value":0, "cost":"SIN COSTE", "atk":0, "hp":5, "sigils":["SPRINTER"], "seal":"CORREDOR", "special_stat":"NONE", "special_abilities":["PackMule"], "traits":["Uncuttable"], "tribes":["Hooved"], "rare":false, "rewardable":false, "playable":false, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":4, "visual_row":1, "visual_col":4},
	{"id":"rata_mochilera", "name":"RATA MOCHILERA", "source_id":"PackRat", "resource":"blood", "cost_value":2, "cost":"2 SANGRE", "atk":2, "hp":2, "sigils":["TRINKET_BEARER"], "seal":"PORTADOR DE OBJETO", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":[], "rare":true, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":4, "visual_row":2, "visual_col":1},
	{"id":"puercoespin", "name":"PUERCOESPÍN", "source_id":"Porcupine", "resource":"blood", "cost_value":1, "cost":"1 SANGRE", "atk":1, "hp":2, "sigils":["SHARP_QUILLS"], "seal":"ESPINAS", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":[], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":4, "visual_row":2, "visual_col":2},
	{"id":"antilope", "name":"ANTÍLOPE", "source_id":"Pronghorn", "resource":"blood", "cost_value":2, "cost":"2 SANGRE", "atk":1, "hp":3, "sigils":["SPRINTER", "BIFURCATED_STRIKE"], "seal":"CORREDOR", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":["Hooved"], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":4, "visual_row":2, "visual_col":3},
	{"id":"conejo", "name":"CONEJO", "source_id":"Rabbit", "resource":"none", "cost_value":0, "cost":"SIN COSTE", "atk":0, "hp":1, "sigils":[], "seal":"NINGUNO", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":[], "rare":false, "rewardable":false, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":4, "visual_row":2, "visual_col":4},
	{"id":"pelaje_de_conejo", "name":"PELAJE DE CONEJO", "source_id":"PeltHare", "resource":"none", "cost_value":0, "cost":"SIN COSTE", "atk":0, "hp":1, "sigils":[], "seal":"NINGUNO", "special_stat":"NONE", "special_abilities":["SpawnLice"], "traits":["Pelt"], "tribes":[], "rare":false, "rewardable":false, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":4, "visual_row":3, "visual_col":1},
	{"id":"rey_rata", "name":"REY RATA", "source_id":"RatKing", "resource":"blood", "cost_value":2, "cost":"2 SANGRE", "atk":2, "hp":1, "sigils":["BONE_KING"], "seal":"REY DE HUESOS", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":[], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":4, "visual_row":3, "visual_col":2},
	{"id":"cascabel", "name":"CASCABEL", "source_id":"Rattler", "resource":"bones", "cost_value":6, "cost":"6 HUESOS", "atk":3, "hp":1, "sigils":[], "seal":"NINGUNO", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":["Reptile"], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":4, "visual_row":3, "visual_col":3},
	{"id":"cuervo", "name":"CUERVO", "source_id":"Raven", "resource":"blood", "cost_value":2, "cost":"2 SANGRE", "atk":2, "hp":3, "sigils":["AIRBORNE"], "seal":"AÉREO", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":["Bird"], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":4, "visual_row":3, "visual_col":4},
	{"id":"huevo_de_cuervo", "name":"HUEVO DE CUERVO", "source_id":"RavenEgg", "resource":"blood", "cost_value":1, "cost":"1 SANGRE", "atk":0, "hp":2, "sigils":["FLEDGLING"], "seal":"CRÍA", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":["Bird"], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"cuervo", "evolve_turns":1, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":4, "visual_row":4, "visual_col":1},
	{"id":"gusano_de_anillo", "name":"GUSANO DE ANILLO", "source_id":"RingWorm", "resource":"blood", "cost_value":1, "cost":"1 SANGRE", "atk":0, "hp":1, "sigils":[], "seal":"NINGUNO", "special_stat":"NONE", "special_abilities":[], "traits":["SatisfiesRingTrial", "KillsSurvivors", "DeathcardCreationNonOption"], "tribes":["Insect"], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":4, "visual_row":4, "visual_col":2},
	{"id":"nutria_de_rio", "name":"NUTRIA DE RÍO", "source_id":"Otter", "resource":"blood", "cost_value":1, "cost":"1 SANGRE", "atk":1, "hp":1, "sigils":["WATERBORNE"], "seal":"SUMERGIBLE", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":[], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":4, "visual_row":4, "visual_col":3},
	{"id":"tortuga_mordedora", "name":"TORTUGA MORDEDORA", "source_id":"Snapper", "resource":"blood", "cost_value":2, "cost":"2 SANGRE", "atk":1, "hp":6, "sigils":[], "seal":"NINGUNO", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":["Reptile"], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":4, "visual_row":4, "visual_col":4},
	{"id":"escinco", "name":"ESCINCO", "source_id":"Skink", "resource":"blood", "cost_value":1, "cost":"1 SANGRE", "atk":1, "hp":2, "sigils":["LOOSE_TAIL"], "seal":"COLA SUELTA", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":["Reptile"], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"cola_retorcida", "counts_as_ant":false, "visual_page":5, "visual_row":1, "visual_col":1},
	{"id":"mofeta", "name":"MOFETA", "source_id":"Skunk", "resource":"blood", "cost_value":1, "cost":"1 SANGRE", "atk":0, "hp":3, "sigils":["STINKY"], "seal":"HEDOR", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":[], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":5, "visual_row":1, "visual_col":2},
	{"id":"abeto_nevado", "name":"ABETO NEVADO", "source_id":"Tree_SnowCovered", "resource":"none", "cost_value":0, "cost":"SIN COSTE", "atk":0, "hp":4, "sigils":["MIGHTY_LEAP"], "seal":"SALTO PODEROSO", "special_stat":"NONE", "special_abilities":[], "traits":["Structure", "Terrain"], "tribes":[], "rare":false, "rewardable":false, "playable":false, "structure":true, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":5, "visual_row":1, "visual_col":3},
	{"id":"gorrion", "name":"GORRIÓN", "source_id":"Sparrow", "resource":"blood", "cost_value":1, "cost":"1 SANGRE", "atk":1, "hp":2, "sigils":["AIRBORNE"], "seal":"AÉREO", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":["Bird"], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":5, "visual_row":1, "visual_col":4},
	{"id":"calamar_campana", "name":"CALAMAR CAMPANA", "source_id":"SquidBell", "resource":"blood", "cost_value":2, "cost":"2 SANGRE", "atk":0, "hp":3, "sigils":[], "seal":"NINGUNO", "special_stat":"BELL", "special_abilities":["BellProximity"], "traits":[], "tribes":[], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":5, "visual_row":2, "visual_col":1},
	{"id":"calamar_de_cartas", "name":"CALAMAR DE CARTAS", "source_id":"SquidCards", "resource":"blood", "cost_value":1, "cost":"1 SANGRE", "atk":0, "hp":1, "sigils":[], "seal":"NINGUNO", "special_stat":"CARDS_IN_HAND", "special_abilities":["CardsInHand"], "traits":[], "tribes":[], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":5, "visual_row":2, "visual_col":2},
	{"id":"calamar_espejo", "name":"CALAMAR ESPEJO", "source_id":"SquidMirror", "resource":"blood", "cost_value":1, "cost":"1 SANGRE", "atk":0, "hp":3, "sigils":[], "seal":"NINGUNO", "special_stat":"MIRROR", "special_abilities":["Mirror"], "traits":[], "tribes":[], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":5, "visual_row":2, "visual_col":3},
	{"id":"ardilla", "name":"ARDILLA", "source_id":"Squirrel", "resource":"none", "cost_value":0, "cost":"SIN COSTE", "atk":0, "hp":1, "sigils":[], "seal":"NINGUNO", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":["Squirrel"], "rare":false, "rewardable":false, "playable":true, "structure":false, "side_deck":true, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":5, "visual_row":2, "visual_col":4},
	{"id":"hambruna", "name":"HAMBRUNA", "source_id":"Starvation", "resource":"none", "cost_value":0, "cost":"SIN COSTE", "atk":1, "hp":1, "sigils":["REPULSIVE"], "seal":"REPULSIVO", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":[], "rare":false, "rewardable":false, "playable":false, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":5, "visual_row":3, "visual_col":1},
	{"id":"hambruna_voladora", "name":"HAMBRUNA VOLADORA", "source_id":"", "resource":"none", "cost_value":0, "cost":"SIN COSTE", "atk":3, "hp":4, "sigils":["REPULSIVE", "AIRBORNE"], "seal":"REPULSIVO", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":[], "rare":false, "rewardable":false, "playable":false, "structure":false, "side_deck":false, "special_only":true, "boss_only":false, "enemy_only":true, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":5, "visual_row":3, "visual_col":2},
	{"id":"chinche_apestosa", "name":"CHINCHE APESTOSA", "source_id":"Stinkbug_Talking", "resource":"bones", "cost_value":2, "cost":"2 HUESOS", "atk":1, "hp":2, "sigils":["STINKY"], "seal":"HEDOR", "special_stat":"NONE", "special_abilities":["TalkingCardChooser"], "traits":["DeathcardCreationNonOption"], "tribes":["Insect"], "rare":false, "rewardable":false, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":5, "visual_row":3, "visual_col":3},
	{"id":"armino", "name":"ARMIÑO", "source_id":"Stoat_Talking", "resource":"blood", "cost_value":1, "cost":"1 SANGRE", "atk":1, "hp":3, "sigils":[], "seal":"NINGUNO", "special_stat":"NONE", "special_abilities":["TalkingCardChooser"], "traits":["DeathcardCreationNonOption"], "tribes":[], "rare":false, "rewardable":false, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":5, "visual_row":3, "visual_col":4},
	{"id":"rana_extrana", "name":"RANA EXTRAÑA", "source_id":"TrapFrog", "resource":"blood", "cost_value":1, "cost":"1 SANGRE", "atk":1, "hp":2, "sigils":["MIGHTY_LEAP"], "seal":"SALTO PODEROSO", "special_stat":"NONE", "special_abilities":["TrapSpawner"], "traits":["Structure", "Terrain"], "tribes":["Reptile"], "rare":false, "rewardable":false, "playable":false, "structure":true, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"trampa_saltarina", "tail_spawn":"", "counts_as_ant":false, "visual_page":5, "visual_row":4, "visual_col":1},
	{"id":"larva_extrana", "name":"LARVA EXTRAÑA", "source_id":"Mothman_Stage1", "resource":"blood", "cost_value":1, "cost":"1 SANGRE", "atk":0, "hp":3, "sigils":["FLEDGLING"], "seal":"CRÍA", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":["Insect"], "rare":true, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"pupa_extrana", "evolve_turns":1, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":5, "visual_row":4, "visual_col":2},
	{"id":"pupa_extrana", "name":"PUPA EXTRAÑA", "source_id":"Mothman_Stage2", "resource":"blood", "cost_value":1, "cost":"1 SANGRE", "atk":0, "hp":3, "sigils":["FLEDGLING"], "seal":"CRÍA", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":["Insect"], "rare":false, "rewardable":false, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"hombre_polilla", "evolve_turns":1, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":5, "visual_row":4, "visual_col":3},
	{"id":"tocon", "name":"TOCÓN", "source_id":"Stump", "resource":"none", "cost_value":0, "cost":"SIN COSTE", "atk":0, "hp":3, "sigils":[], "seal":"NINGUNO", "special_stat":"NONE", "special_abilities":[], "traits":["Structure", "Terrain"], "tribes":[], "rare":false, "rewardable":false, "playable":false, "structure":true, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":5, "visual_row":4, "visual_col":4},
	{"id":"plumas_de_cola", "name":"PLUMAS DE COLA", "source_id":"Tail_Bird", "resource":"none", "cost_value":0, "cost":"SIN COSTE", "atk":0, "hp":2, "sigils":[], "seal":"NINGUNO", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":[], "rare":false, "rewardable":false, "playable":false, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":6, "visual_row":1, "visual_col":1},
	{"id":"los_daus", "name":"LOS DAUS", "source_id":"Daus", "resource":"blood", "cost_value":2, "cost":"2 SANGRE", "atk":2, "hp":2, "sigils":["BELLIST"], "seal":"CAMPANERO", "special_stat":"NONE", "special_abilities":["Daus"], "traits":[], "tribes":["Hooved"], "rare":true, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":6, "visual_row":1, "visual_col":2},
	{"id":"el_humo", "name":"EL HUMO", "source_id":"Smoke", "resource":"none", "cost_value":0, "cost":"SIN COSTE", "atk":0, "hp":1, "sigils":["BONE_KING"], "seal":"REY DE HUESOS", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":[], "rare":false, "rewardable":false, "playable":false, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":6, "visual_row":1, "visual_col":3},
	{"id":"buitre_pavo", "name":"BUITRE PAVO", "source_id":"Vulture", "resource":"bones", "cost_value":8, "cost":"8 HUESOS", "atk":3, "hp":3, "sigils":["AIRBORNE"], "seal":"AÉREO", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":["Bird"], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":6, "visual_row":1, "visual_col":4},
	{"id":"gato_no_muerto", "name":"GATO NO MUERTO", "source_id":"CatUndead", "resource":"blood", "cost_value":1, "cost":"1 SANGRE", "atk":3, "hp":6, "sigils":[], "seal":"NINGUNO", "special_stat":"NONE", "special_abilities":[], "traits":["Undead"], "tribes":[], "rare":false, "rewardable":false, "playable":false, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":6, "visual_row":2, "visual_col":1},
	{"id":"urayuli", "name":"URAYULI", "source_id":"Urayuli", "resource":"blood", "cost_value":4, "cost":"4 SANGRE", "atk":7, "hp":7, "sigils":[], "seal":"NINGUNO", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":[], "rare":true, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":6, "visual_row":2, "visual_col":2},
	{"id":"madriguera", "name":"MADRIGUERA", "source_id":"Warren", "resource":"blood", "cost_value":1, "cost":"1 SANGRE", "atk":0, "hp":2, "sigils":["RABBIT_HOLE"], "seal":"MADRIGUERA DE CONEJOS", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":[], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":6, "visual_row":2, "visual_col":3},
	{"id":"lobo", "name":"LOBO", "source_id":"Wolf", "resource":"blood", "cost_value":2, "cost":"2 SANGRE", "atk":3, "hp":2, "sigils":[], "seal":"NINGUNO", "special_stat":"NONE", "special_abilities":[], "traits":["Wolf"], "tribes":["Canine"], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":6, "visual_row":2, "visual_col":4},
	{"id":"cachorro_de_lobo", "name":"CACHORRO DE LOBO", "source_id":"WolfCub", "resource":"blood", "cost_value":1, "cost":"1 SANGRE", "atk":1, "hp":1, "sigils":["FLEDGLING"], "seal":"CRÍA", "special_stat":"NONE", "special_abilities":[], "traits":["Wolf"], "tribes":["Canine"], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"lobo", "evolve_turns":1, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":6, "visual_row":3, "visual_col":1},
	{"id":"pelaje_de_lobo", "name":"PELAJE DE LOBO", "source_id":"PeltWolf", "resource":"none", "cost_value":0, "cost":"SIN COSTE", "atk":0, "hp":2, "sigils":[], "seal":"NINGUNO", "special_stat":"NONE", "special_abilities":["SpawnLice"], "traits":["Pelt"], "tribes":[], "rare":false, "rewardable":false, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":6, "visual_row":3, "visual_col":2},
	{"id":"lobo_parlante", "name":"LOBO PARLANTE", "source_id":"Wolf_Talking", "resource":"blood", "cost_value":1, "cost":"1 SANGRE", "atk":2, "hp":2, "sigils":[], "seal":"NINGUNO", "special_stat":"NONE", "special_abilities":["TalkingCardChooser"], "traits":["DeathcardCreationNonOption"], "tribes":["Canine"], "rare":false, "rewardable":false, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":6, "visual_row":3, "visual_col":3},
	{"id":"hormiga_obrera", "name":"HORMIGA OBRERA", "source_id":"Ant", "resource":"blood", "cost_value":1, "cost":"1 SANGRE", "atk":0, "hp":2, "sigils":[], "seal":"NINGUNO", "special_stat":"ANTS", "special_abilities":["Ant"], "traits":["Ant"], "tribes":["Insect"], "rare":false, "rewardable":true, "playable":true, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":true, "visual_page":6, "visual_row":3, "visual_col":4},
	{"id":"pata_retorcida", "name":"PATA RETORCIDA", "source_id":"Tail_Insect", "resource":"none", "cost_value":0, "cost":"SIN COSTE", "atk":0, "hp":2, "sigils":[], "seal":"NINGUNO", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":[], "rare":false, "rewardable":false, "playable":false, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":6, "visual_row":4, "visual_col":2},
	{"id":"cola_retorcida", "name":"COLA RETORCIDA", "source_id":"SkinkTail", "resource":"none", "cost_value":0, "cost":"SIN COSTE", "atk":0, "hp":2, "sigils":[], "seal":"NINGUNO", "special_stat":"NONE", "special_abilities":[], "traits":[], "tribes":["Reptile"], "rare":false, "rewardable":false, "playable":false, "structure":false, "side_deck":false, "special_only":false, "boss_only":false, "enemy_only":false, "evolve_to":"", "evolve_turns":0, "death_spawn":"", "tail_spawn":"", "counts_as_ant":false, "visual_page":6, "visual_row":4, "visual_col":3}
]

static func find_by_id(card_id: String) -> Dictionary:
	for card in CARDS:
		if str(card.get("id", "")) == card_id:
			return card.duplicate(true)
	return {}

static func all_cards() -> Array[Dictionary]:
	var result: Array[Dictionary] = []
	for card in CARDS:
		result.append(card.duplicate(true))
	return result

static func all_card_ids() -> Array[String]:
	var result: Array[String] = []
	for card in CARDS:
		result.append(str(card.get("id", "")))
	return result

static func campaign_reward_pool() -> Array[String]:
	var result: Array[String] = []
	for card in CARDS:
		if bool(card.get("rewardable", false)) and bool(card.get("playable", false)):
			result.append(str(card.get("id", "")))
	return result

static func playable_pool() -> Array[String]:
	var result: Array[String] = []
	for card in CARDS:
		if bool(card.get("playable", false)) and not bool(card.get("side_deck", false)):
			result.append(str(card.get("id", "")))
	return result

static func sigil_name(code: String) -> String:
	return str(SIGIL_NAMES.get(code, code.replace("_", " ")))

static func has_sigil(card: Dictionary, code: String) -> bool:
	return Array(card.get("sigils", [])).has(code)
